site_name: aitextgen
site_description: A robust Python tool for text-based AI training and generation using GPT-2 and GPT Neo.
site_author: Max Woolf (@minimaxir)

nav:
  - Home: index.md
  - Hello World Tutorial: tutorials/hello-world.md
  - Loading a Model: load-model.md
  - Saving a Model: save-model.md
  - TokenDataset: dataset.md
  - Training a Model:
      - Colaboratory Notebooks: tutorials/colab.md
      # - Improving Training Performance: train-performance.md
      - Training a GPT-2 Model From Scratch: tutorials/model-from-scratch.md
      - Loggers: loggers.md
  - Generating from a Model:
      - Generating Text: generate.md
      # - Improving Generation Performance: generate-performance.md
      # - Generating From GPT-2 1.5B: tutorials/generate_1_5b.md
  - Importing from gpt-2-simple: gpt-2-simple.md
  - Helpful Notes: helpful-notes.md
  - Ethics: ethics.md
  - Command-Line Interface: cli.md
  - Upload Model to Huggingface: upload.md

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Source Sans Pro"
    code: "Fira Code"
  features:
    - tabs
    - instant
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

repo_name: minimaxir/aitextgen
repo_url: https://github.com/minimaxir/aitextgen
edit_uri: ""

copyright: "Copyright &copy; 2019 - 2021 Max Woolf"

extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/minimaxir/aitextgen"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/minimaxir"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true
